services:
  postgresql:    
    image: postgres:16-alpine
    env_file:
      - backend/.env     
    container_name: postgresql  
    hostname: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ktpm
      POSTGRES_PASSWORD: ktpm
      POSTGRES_DB: ktpm
    volumes: 
      - ktpm:/var/lib/postgresql/data      
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    hostname: backend
    env_file:
      - backend/.env 
    depends_on:
      - postgresql
    environment:
      POSTGRES_USER: ktpm
      POSTGRES_PASSWORD: ktpm
      POSTGRES_DB: ktpm
      DATABASE_URL: postgresql://ktpm:ktpm@postgresql:5432/ktpm
      SECRET_KEY: secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8000

volumes:
  ktpm: