services:
  postgresql:
    # Set wal_level from replica (default) to logical
    # so that Debezium can capture change
    image: postgres:16-alpine
    env_file:
      - .env 
    command: ['postgres', '-c', 'wal_level=logical']
    container_name: postgresql  
    hostname: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - ktpm:/var/lib/postgresql/data
      #- init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    volumes:
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        mkdir -p /var/lib/pgadmin/storage/admin_example.com/
        cp /pgadmin4/servers.json /var/lib/pgadmin/storage/admin_example.com/servers.json
        /entrypoint.sh

  # fastapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   container_name: fastapi
  #   hostname: fastapi
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - postgresql
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     DATABASE_URL: postgresql://ktpm:ktpm@postgresql:5432/ktpm
  #     SECRET_KEY: ${SECRET_KEY}
  #     ALGORITHM: ${ALGORITHM}
  #     ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  ktpm: